In [1]:
import pandas as pd

df = pd.read_csv('../data/invoices.csv')
df.head()

,file,x0,y0,x1,y1,x2,y2,x3,y3,text,entities,labels
0,X51006555072.jpg,106,179,502,179,502,204,106,204,DIGI TELECOMMUNICATIONS SDN BHD,"{\n ""company"": ""DIGI TELECOMMUNICATIONS SDN...",ambiguous
1,X51006555072.jpg,239,205,364,205,364,231,239,231,(201283-M),"{\n ""company"": ""DIGI TELECOMMUNICATIONS SDN...",ambiguous
2,X51006555072.jpg,80,229,539,229,539,256,80,256,"LOT LG 315, 1-UTAMA SHOPPING CENTRE,","{\n ""company"": ""DIGI TELECOMMUNICATIONS SDN...",ambiguous
3,X51006555072.jpg,98,255,499,255,499,280,98,280,"LEBUH BANDAR UTAMA-BANDAR UTAMA,","{\n ""company"": ""DIGI TELECOMMUNICATIONS SDN...",ambiguous
4,X51006555072.jpg,172,278,429,278,429,307,172,307,"PETALING JAYA, 47800","{\n ""company"": ""DIGI TELECOMMUNICATIONS SDN...",ambiguous

## 1. Testing Heuristics

In [2]:
df['extracted_number_INV#'] = df['text'].str.extract(r'INV#\s*([^\s]+)')
df[df['extracted_number_INV#'].notnull()]

,file,x0,y0,x1,y1,x2,y2,x3,y3,text,entities,labels,extracted_number_INV#
1291,X51006913068.jpg,1512,2642,2224,2642,2224,2729,1512,2729,INV# 000960100030435,"{\n ""company"": ""GERBANG ALAF RESTAURANTS SD...",000960100030435,000960100030435
1367,X51006619772.jpg,15,734,422,734,422,774,15,774,INV# 002511900048269,"{\n ""company"": ""GOLDEN ARCHES RESTAURANTS S...",002511900048269,002511900048269
2404,X51007846395.jpg,1526,2859,2336,2859,2336,2937,1526,2937,INV# 003090200024723,"{\n ""company"": ""GERBANG ALAF RESTAURANTS SD...",003090200024723,003090200024723
2890,X51005712017.jpg,26,498,306,498,306,528,26,528,INV# 001881904580783,"{\n ""company"": ""GERBANG ALAF RESTAURANTS SD...",001881904580783,001881904580783
4298,X51005711453.jpg,28,1001,395,1001,395,1045,28,1045,INV# 003621900059183,"{\n ""company"": ""GERBANG ALAF RESTAURANTS SD...",003621900059183,003621900059183
5993,X51005711452.jpg,46,911,410,911,410,952,46,952,INV# 003621900066840,"{\n ""company"": ""GERBANG ALAF RESTAURANTS SD...",003621900066840,003621900066840
11708,X51006334926.jpg,29,964,343,964,343,996,29,996,INV# 001780200112117,"{\n ""company"": ""GOLDEN ARCHES RESTAURANTS S...",001780200112117,001780200112117
13366,X51008042783.jpg,27,787,336,787,336,821,27,821,INV# 003621900031366,"{\n ""company"": ""GERBANG ALAF RESTAURANTS SD...",003621900031366,003621900031366
15431,X51005717526.jpg,21,559,297,559,297,598,21,598,INV# 001881904569068,"{\n ""company"": ""GERBANG ALAF RESTAURANTS SD...",001881904569068,001881904569068
17875,X51007262315.jpg,14,673,284,673,284,702,14,702,INV# 003281900047036,"{\n ""company"": ""GERBANG ALAF RESTAURANTS SD...",003281900047036,003281900047036
23557,X51005230617.jpg,6,681,275,681,275,710,6,710,INV# 003281900229170,"{\n ""company"": ""GERBANG ALAF RESTAURANTS SD...",003281900229170,003281900229170
28998,X51006414636.jpg,1625,2399,1802,2399,1802,2474,1625,2474,INV#:,"{\n ""company"": ""SELASIH EKSLUSIF SDN BHD"",\...",J100086182-0000000J10000087385,:

In [8]:
# Heuristic 1: INV#
df['extracted_number_INV#'] = df['text'].str.extract(r'INV#\s*:?\s*([A-Za-z0-9/\-]+)')
df[df['extracted_number_INV#'].notnull()]
print(f'Heuristic "INV#": {len(df[df["extracted_number_INV#"].notnull()])} / {df.file.nunique()} ({len(df)})')

# Heuristic 2: INV:
df['extracted_number_INV'] = df['text'].str.extract(r'INV:\s*([^\s]+)')
df[df['extracted_number_INV'].notnull()]
print(f'Heuristic "INV:": {len(df[df["extracted_number_INV"].notnull()])} / {df.file.nunique()} ({len(df)})')

# Heuristic 3: INV-NO.
df['extracted_number_INV-NO'] = df['text'].str.extract(r'INV-NO\.\s*([^\s]+)')
df[df['extracted_number_INV-NO'].notnull()]
print(f'Heuristic "INV-NO": {len(df[df["extracted_number_INV-NO"].notnull()])} / {df.file.nunique()} ({len(df)})')

# Heuristic 4: INV NO
df['extracted_number_INV_NO'] = df['text'].str.extract(r'INV\s*NO\.?\s*[:\-]?\s*([A-Za-z0-9/\-]+)')
df[df['extracted_number_INV_NO'].notnull()]
print(f'Heuristic "INV NO": {len(df[df["extracted_number_INV_NO"].notnull()])} / {df.file.nunique()} ({len(df)})')

# Heuristic 5: Slip
df['extracted_number_Slip'] = df['text'].str.extract(r'SLIP\s*(?:NO\.?|NUMBER)?\s*[^A-Za-z0-9]*\s*([A-Za-z0-9/\-]+)')
df[df['extracted_number_Slip'].notnull()]
print(f'Heuristic "SLIP": {len(df[df["extracted_number_Slip"].notnull()])} / {df.file.nunique()} ({len(df)})')

# Heuristic 6: INVOICE NO
df['extracted_number_INVOICE_NO'] = df['text'].str.extract(r'INVOICE\s*NO\s*[:\-]?\s*([A-Za-z0-9/\-_]+)')
df[df['extracted_number_INVOICE_NO'].notnull()]
print(f'Heuristic "INVOICE NO": {len(df[df["extracted_number_INVOICE_NO"].notnull()])} / {df.file.nunique()} ({len(df)})')

# Heuristic 7: RECEIPT NO.
df['extracted_number_RECEIPT_NO'] = df['text'].str.extract(r'RECEIPT\s*NO\s*[:\-]?\s*([A-Za-z0-9/\-]+)')
df[df['extracted_number_RECEIPT_NO'].notnull()]
print(f'Heuristic "RECEIPT NO": {len(df[df["extracted_number_RECEIPT_NO"].notnull()])} / {df.file.nunique()} ({len(df)})')

# Heuristic 8: CB# : 
df['extracted_number_CB#'] = df['text'].str.extract(r'CB# :\s*([A-Za-z0-9/\-]+)')
df[df['extracted_number_CB#'].notnull()]
print(f'Heuristic "CB# :": {len(df[df["extracted_number_CB#"].notnull()])} / {df.file.nunique()} ({len(df)})')

# Heursitic 9: BILL NO
df['extracted_number_BILL_NO'] = df['text'].str.extract(r'BILL\s*NO\s*[:\-]?\s*([A-Za-z0-9/\-]+)')
df[df['extracted_number_BILL_NO'].notnull()]
print(f'Heuristic "BILL NO": {len(df[df["extracted_number_BILL_NO"].notnull()])} / {df.file.nunique()} ({len(df)})')

# Heuristic 10: INVOICE #
df['extracted_number_INVOICE#'] = df['text'].str.extract(r'INVOICE\s*#\s*:?[\s]*([A-Za-z0-9/\-]+)')
df[df['extracted_number_INVOICE#'].notnull()]
print(f'Heuristic "INVOICE#": {len(df[df["extracted_number_INVOICE#"].notnull()])} / ({df.file.nunique()} ({len(df)}')  

# Heuristic 11: C/N NO:
df['extracted_number_CN_NO'] = df['text'].str.extract(r'C/N\s*NO\s*[:\-]?\s*([A-Za-z0-9/\-]+)')
df[df['extracted_number_CN_NO'].notnull()]
print(f'Heuristic "C/N NO": {len(df[df["extracted_number_CN_NO"].notnull()])} / {df.file.nunique()} ({len(df)})')

# Heuristic 12: TRANSACTION NO:
df['extracted_number_TRANSACTION_NO'] = df['text'].str.extract(r'TRANSACTION\s*NO\s*[:\-]?\s*([A-Za-z0-9/\-]+)')
df[df['extracted_number_TRANSACTION_NO'].notnull()]
print(f'Heuristic "TRANSACTION NO": {len(df[df["extracted_number_TRANSACTION_NO"].notnull()])} / {df.file.nunique()} ({len(df)})')

# Heuristic 13: TRN:
df['extracted_number_TRN'] = df['text'].str.extract(r'TRN\s*[:\-]?\s*([A-Za-z0-9/\-]+)')
df[df['extracted_number_TRN'].notnull()]
print(f'Heuristic "TRN": {len(df[df["extracted_number_TRN"].notnull()])} / {df.file.nunique()} ({len(df)})')

# Heuristic 14: RCPT
df['extracted_number_RCPT'] = df['text'].str.extract(r'RCPT#\s*:\s*([A-Za-z0-9]+)')
df[df['extracted_number_RCPT'].notnull()]
print(f'Heuristic "RCPT": {len(df[df["extracted_number_RCPT"].notnull()])} / {df.file.nunique()} ({len(df)})')

#TODO: Potential heuristics to add
# Receipt # (X51005200931)

Heuristic "INV#": 11 / 626 (33626)
Heuristic "INV:": 10 / 626 (33626)
Heuristic "INV-NO": 4 / 626 (33626)
Heuristic "INV NO": 123 / 626 (33626)
Heuristic "SLIP": 15 / 626 (33626)
Heuristic "INVOICE NO": 64 / 626 (33626)
Heuristic "RECEIPT NO": 5 / 626 (33626)
Heuristic "CB# :": 6 / 626 (33626)
Heuristic "BILL NO": 7 / 626 (33626)
Heuristic "INVOICE#": 42 / (626 (33626
Heuristic "C/N NO": 1 / 626 (33626)
Heuristic "TRANSACTION NO": 2 / 626 (33626)
Heuristic "TRN": 4 / 626 (33626)
Heuristic "RCPT": 1 / 626 (33626)

In [16]:
df[
    (df['file'] == 'X51008164525.jpg')
]

,file,x0,y0,x1,y1,x2,y2,x3,y3,text,...,extracted_number_Slip,extracted_number_INVOICE_NO,extracted_number_RECEIPT_NO,extracted_number_CB#,extracted_number_BILL_NO,extracted_number_INVOICE#,extracted_number_CN_NO,extracted_number_TRANSACTION_NO,extracted_number_TRN,extracted_number_RCPT
4345,X51008164525.jpg,192,221,697,221,697,256,192,256,PASAR RAYA MEGA MAJU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4346,X51008164525.jpg,222,266,670,266,670,303,222,303,(SEMENYIH) SDN BHD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4347,X51008164525.jpg,343,315,545,315,545,354,343,354,(767840-W),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4348,X51008164525.jpg,309,364,577,364,577,403,309,403,"NO 24, 25 & 26,",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4349,X51008164525.jpg,78,413,806,413,806,447,78,447,"JALAN PUSAT PERNIAGAAN BUNGA RAYA 4,",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4350,X51008164525.jpg,153,460,733,460,733,496,153,496,"PUSAT PERNIAGAAN BUNGA RAYA,",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4351,X51008164525.jpg,227,506,305,506,305,541,227,541,TEL:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4352,X51008164525.jpg,487,506,560,506,560,537,487,537,FAX:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4353,X51008164525.jpg,230,552,704,552,704,591,230,591,GST REG NO: 000746659840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4354,X51008164525.jpg,61,598,222,598,222,629,61,629,INVOICE NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4355,X51008164525.jpg,255,600,439,600,439,630,255,630,: 01-283886,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4356,X51008164525.jpg,64,647,138,647,138,678,64,678,DATE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4357,X51008164525.jpg,253,646,638,646,638,678,253,678,: 03/07/2018 5:22:43 PM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4358,X51008164525.jpg,64,696,174,696,174,727,64,727,CASHIER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4359,X51008164525.jpg,252,696,339,696,339,725,252,725,: SITI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4360,X51008164525.jpg,332,740,577,740,577,772,332,772,TAX INVOICE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4361,X51008164525.jpg,131,815,301,815,301,850,131,850,DESCRIPTION,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4362,X51008164525.jpg,468,817,521,817,521,849,468,849,QTY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4363,X51008164525.jpg,583,816,660,816,660,844,583,844,PRICE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4364,X51008164525.jpg,708,817,825,817,825,843,708,843,AMOUNT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4365,X51008164525.jpg,80,861,97,861,97,891,80,891,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4366,X51008164525.jpg,76,951,94,951,94,982,76,982,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4367,X51008164525.jpg,111,860,427,860,427,888,111,888,SRO 9555544201075,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4368,X51008164525.jpg,105,906,554,906,554,936,105,936,PRO BALANCE 400GM - BEFF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4369,X51008164525.jpg,110,951,427,951,427,980,110,980,SR0 9555544201198,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4370,X51008164525.jpg,104,993,543,993,543,1026,104,1026,PRO BALANCE LAMB 400GM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4371,X51008164525.jpg,500,864,518,864,518,889,500,889,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4372,X51008164525.jpg,497,951,521,951,521,979,497,979,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4373,X51008164525.jpg,591,861,661,861,661,889,591,889,4.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4374,X51008164525.jpg,593,951,660,951,660,978,593,978,4.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4375,X51008164525.jpg,742,859,824,859,824,890,742,890,17.40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4376,X51008164525.jpg,741,951,822,951,822,979,741,979,13.05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4377,X51008164525.jpg,435,1049,521,1049,521,1075,435,1075,TOTAL:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4378,X51008164525.jpg,751,1048,825,1048,825,1073,751,1073,30.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4379,X51008164525.jpg,399,1094,520,1094,520,1122,399,1122,DISCOUNT:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4380,X51008164525.jpg,768,1095,827,1095,827,1123,768,1123,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4381,X51008164525.jpg,55,1141,518,1141,518,1173,55,1173,TOTAL SALES INCLUSIVE GST @0.00%:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4382,X51008164525.jpg,750,1144,824,1144,824,1169,750,1169,30.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4383,X51008164525.jpg,305,1187,518,1187,518,1216,305,1216,CASH RECEIVED :,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4384,X51008164525.jpg,749,1188,824,1188,824,1216,749,1216,30.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4385,X51008164525.jpg,403,1234,520,1234,520,1265,403,1265,CHANGE :,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4386,X51008164525.jpg,767,1234,825,1234,825,1259,767,1259,0.05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4387,X51008164525.jpg,87,1305,278,1305,278,1335,87,1335,GST SUMMARY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4388,X51008164525.jpg,349,1305,376,1305,376,1331,349,1331,%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4389,X51008164525.jpg,470,1304,636,1304,636,1332,470,1332,AMOUNT(RM),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4390,X51008164525.jpg,684,1303,799,1303,799,1332,684,1332,TAX(RM),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4391,X51008164525.jpg,85,1351,142,1351,142,1376,85,1376,SR0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4392,X51008164525.jpg,319,1349,379,1349,379,1377,319,1377,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4393,X51008164525.jpg,562,1351,636,1351,636,1378,562,1378,30.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4394,X51008164525.jpg,744,1350,802,1350,802,1378,744,1378,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4395,X51008164525.jpg,194,1456,666,1456,666,1490,194,1490,THANK YOU. PLEASE COME AGAIN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4396,X51008164525.jpg,201,1501,663,1501,663,1539,201,1539,TERIMA KASIH. SILA DATANG LAGI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4397,X51008164525.jpg,103,1546,779,1546,779,1578,103,1578,GOOD SOLD ARE NOT REFUNABLE AND RETURNABLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df[df['extracted_number_TRANSACTION_NO'].notnull()]

,file,x0,y0,x1,y1,x2,y2,x3,y3,text,...,extracted_number_Slip,extracted_number_INVOICE_NO,extracted_number_RECEIPT_NO,extracted_number_CB#,extracted_number_BILL_NO,extracted_number_INVOICE#,extracted_number_CN_NO,extracted_number_TRANSACTION_NO,extracted_number_TRN,extracted_number_RCPT
13070,X51005742068.jpg,43,715,430,715,430,749,43,749,TRANSACTION NO: 1-8046,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1-8046,NaN,NaN
22900,X51006414533.jpg,1753,3218,2710,3218,2710,3314,1753,3314,TRANSACTION NO: 1-494268,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1-494268,NaN,NaN

## 2. Postprocessing

In [44]:
import numpy as np

extracted_cols = [col for col in df.columns if col.startswith('extracted_number_')]

df['extract_numbers'] = df[extracted_cols].apply(
    lambda row: ','.join(str(x) for x in row if pd.notna(x)),
    axis=1
)

# Group by file and combine multiple rows per file, deduplicating numbers
df_grouped = df.groupby('file')['extract_numbers'].agg(
    lambda s: ','.join(
        dict.fromkeys(
            [t.strip() for t in ','.join(s).split(',') if t.strip()]
        )
    )
).reset_index()


df_grouped['extract_numbers'] = df_grouped['extract_numbers'].replace('', np.nan)
df_grouped.head(10)

## TODO: remove parentheses: (INV123)

               file  extract_numbers
0  X00016469612.jpg              NaN
1  X00016469619.jpg              NaN
2  X00016469620.jpg              NaN
3  X00016469622.jpg              NaN
4  X00016469623.jpg              NaN
5  X00016469669.jpg              NaN
6  X00016469672.jpg              NaN
7  X00016469676.jpg            22497
8  X51005200938.jpg              NaN
9  X51005230617.jpg  003281900229170

In [45]:
df_grouped[df_grouped.extract_numbers.str.contains(',', na=False)]

                file  extract_numbers
59  X51005442397.jpg  REC-0015016,REC

In [47]:
import json
with open('../data/labels.json', 'r') as f:
    labels = json.load(f)

# Convert dictionary to DataFrame
label_df = pd.DataFrame(list(labels.items()), columns=['file', 'label'])

result_df = pd.merge(df_grouped, label_df, on='file', how='left')
result_df.head(10)

               file  extract_numbers            label
0  X00016469612.jpg              NaN       TD01167104
1  X00016469619.jpg              NaN          MO26588
2  X00016469620.jpg              NaN        ambiguous
3  X00016469622.jpg              NaN       CS00031663
4  X00016469623.jpg              NaN        ambiguous
5  X00016469669.jpg              NaN        01-143008
6  X00016469672.jpg              NaN       CS00004040
7  X00016469676.jpg            22497            22497
8  X51005200938.jpg              NaN       CS00082662
9  X51005230617.jpg  003281900229170  003281900229170

In [48]:
# Check where labels are null
result_df[result_df['label'].isnull()]

Empty DataFrame
Columns: [file, extract_numbers, label]
Index: []

In [49]:
ct_correct = (result_df['extract_numbers'] == result_df['label']).sum()
print(f"Correct: {ct_correct} / {len(result_df)}")
print(f"Accuracy: {ct_correct / len(result_df):.2%}")

# count how many 'ambiguous' labels there are
ambiguous_count = sum(1 for label in labels.values() if 'ambiguous' in label)
print(f"Number of ambiguous labels: {ambiguous_count} / {len(result_df)}")

# check where it was wrong and extract_numbers is not null
print("Wrong predictions where both label and extract_numbers are non-null:")
wrong_df = result_df[(result_df['extract_numbers'] != result_df['label']) & (result_df['extract_numbers'].notnull()) & (result_df['label'].notnull())]
wrong_df

Correct: 290 / 626
Accuracy: 46.33%
Number of ambiguous labels: 72 / 626
Wrong predictions where both label and extract_numbers are non-null:

                 file  extract_numbers         label
59   X51005442397.jpg  REC-0015016,REC   REC-0015016
130  X51005677339.jpg             ABLE    CS00065374
381  X51006619545.jpg            /DATE   K074-001096
397  X51006619785.jpg            /DATE  15403-119386

## 3. Validating Heuristics

1. Labels must be > 3 characters 
2. Labels cannot contain no numbers
3. Any extracted label that have multiple values

In [50]:
# filter result_df for extract_numbers that are <= 3 characters and non null
filtered_df = result_df[result_df['extract_numbers'].notnull() & (result_df['extract_numbers'].str.len() <= 3)]
filtered_df # X51005719899 is an anomaly

                 file extract_numbers label
167  X51005719899.jpg               1     1

In [51]:
# filter result df for extract_numbers that contain no numbers
filtered_df = result_df[result_df['extract_numbers'].notnull() & (~result_df['extract_numbers'].str.contains(r'\d', na=False))]
filtered_df

                 file extract_numbers         label
130  X51005677339.jpg            ABLE    CS00065374
381  X51006619545.jpg           /DATE   K074-001096
397  X51006619785.jpg           /DATE  15403-119386

In [52]:
# filter result_df for extract_numbers that contain a comma
filtered_df = result_df[result_df['extract_numbers'].notnull() & (result_df['extract_numbers'].str.contains(',', na=False))]
filtered_df

                file  extract_numbers        label
59  X51005442397.jpg  REC-0015016,REC  REC-0015016